//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAdmins
    {
        public int ConsecutivoAdmin { get; set; }
        public string IdAdmin { get; set; }
        public string NombreAd { get; set; }
        public string ApellidoAd { get; set; }
        public string CorreoAd { get; set; }
        public string TelAd { get; set; }
        public int ConsecutivoRol { get; set; }
    
        public virtual tRoles tRoles { get; set; }
    }
}
