//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmpleados
    {
        public int ConsecutivoEmp { get; set; }
        public string IdEmpleado { get; set; }
        public string NombreEmp { get; set; }
        public string ApellidoEmp { get; set; }
        public string CorreoEmp { get; set; }
        public string TelEmp { get; set; }
        public int ConsecutivoPuesto { get; set; }
        public int ConsecutivoRol { get; set; }
        public bool ActivoEmp { get; set; }
        public string Contraseña { get; set; }
    
        public virtual tPuestos tPuestos { get; set; }
        public virtual tRoles tRoles { get; set; }
    }
}
